updated start script to use latest quickstart env variables for soroban

diff --git a/start b/start
--- a/start
+++ b/start
@@ -62,12 +62,16 @@ function main() {
   process_args "$@"
 
   if [ ! -z "$TARGET_NETWORK_RPC_URL" ] && [ ! -z "$TARGET_NETWORK" ]; then
-      echo "Invalid TargetNetwork config, must be TargetNetwork=standalone|futurenet or TargetNetworkRPCURL, aborting test ..." >&2
+      echo "Invalid TargetNetwork config, must set TargetNetwork or TargetNetworkRPCURL, aborting test ..." >&2
       exit 1
   fi  
 
-  if [ -z "$TARGET_NETWORK_RPC_URL" ] && [ "$TARGET_NETWORK" != "standalone" ] && [ "$TARGET_NETWORK" != "futurenet" && ]; then
-      echo "Invalid TargetNetwork, must be one of standalone or futurenet, aborting test ..." >&2
+  if [ -z "$TARGET_NETWORK_RPC_URL" ] && \
+     [ "$TARGET_NETWORK" != "standalone" ] && \
+     [ "$TARGET_NETWORK" != "local" ] && \
+     [ "$TARGET_NETWORK" != "futurenet" && ] && \
+     [ "$TARGET_NETWORK" != "testnet" && ]; then
+      echo "Invalid TargetNetwork, must be one of: standalone or local(both mean the same), futurenet, or testnet, aborting test ..." >&2
       exit 1
   fi  
 
@@ -186,7 +190,7 @@ function process_args() {
   done
 
   if [ -z "$TARGET_NETWORK_RPC_URL" ] && [ -z "$TARGET_NETWORK" ]; then
-      TARGET_NETWORK=standalone
+      TARGET_NETWORK=local
   fi 
 }
 
@@ -205,7 +209,13 @@ function soroban_rpc_status () {
     if [ $(expr $COUNTER % 12) -eq 0 ]; then 
       print_screen_output "waited $(expr $COUNTER / 12) minutes for soroban rpc to report ready state..." 
     fi
-    COUNTER=$[$COUNTER +1]    
+    COUNTER=$[$COUNTER +1]  
+
+    if [ $COUNTER -gt 900 ]; then
+      echo "Waited longer than 15 minutes for rpc, cancelling and exit."
+      exit
+    fi  
+
     sleep 5
   done 
   print_screen_output "soroban rpc reported ready status, the service can be used by tools/cli now ..." 
